# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtext', models.TextField()),
                ('qlink', models.FileField(blank=True, upload_to='img/')),
                ('answer', models.CharField(max_length=500)),
                ('alink', models.FileField(blank=True, upload_to='img/')),
                ('comment', models.TextField(blank=True)),
                ('source', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_played', models.BooleanField()),
                ('is_video', models.BooleanField()),
                ('is_music', models.BooleanField()),
                ('is_img', models.BooleanField()),
                ('is_bb', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
