# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='alink',
            field=models.FileField(blank=True, upload_to='questionbase/static/img/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qlink',
            field=models.FileField(blank=True, upload_to='questionbase/static/img/'),
        ),
    ]
