# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0002_auto_20170929_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=500, verbose_name='Название пакета')),
                ('pack_date', models.DateTimeField(verbose_name='Дата игры')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='alink',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_img',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_music',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_video',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qlink',
        ),
        migrations.AddField(
            model_name='question',
            name='altanswer',
            field=models.CharField(blank=True, max_length=500, verbose_name='Зачет'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=500, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=500, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_bb',
            field=models.BooleanField(verbose_name='ЧЯ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_played',
            field=models.BooleanField(verbose_name='Игралось'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtext',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='question',
            name='when_played',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionbase.Games', verbose_name='Пакет'),
        ),
    ]
