# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0003_auto_20170930_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='when_played',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
