# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0004_auto_20170930_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='aLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alink', models.FileField(upload_to='questionbase/static/img/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbase.Question')),
            ],
        ),
        migrations.CreateModel(
            name='qLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qlink', models.FileField(upload_to='questionbase/static/img/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbase.Question')),
            ],
        ),
    ]
