# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0006_auto_20171010_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_date',
        ),
    ]
