# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0008_question_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alinks',
            name='alink',
            field=models.FileField(upload_to='questionbase/static/img/answer/', verbose_name='Файл к ответу'),
        ),
        migrations.AlterField(
            model_name='qlinks',
            name='qlink',
            field=models.FileField(upload_to='questionbase/static/img/question/', verbose_name='Файл к вопросу'),
        ),
    ]
