# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0009_auto_20171016_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alinks',
            name='question',
        ),
        migrations.RemoveField(
            model_name='qlinks',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='alink1',
            field=models.FileField(blank=True, upload_to='questionbase/static/img/answer/', verbose_name='Файл к ответу'),
        ),
        migrations.AddField(
            model_name='question',
            name='alink2',
            field=models.FileField(blank=True, upload_to='questionbase/static/img/answer/', verbose_name='Файл к ответу'),
        ),
        migrations.AddField(
            model_name='question',
            name='alink3',
            field=models.FileField(blank=True, upload_to='questionbase/static/img/answer/', verbose_name='Файл к ответу'),
        ),
        migrations.AddField(
            model_name='question',
            name='qlink1',
            field=models.FileField(blank=True, upload_to='questionbase/static/img/question/', verbose_name='Файл к вопросу'),
        ),
        migrations.AddField(
            model_name='question',
            name='qlink2',
            field=models.FileField(blank=True, upload_to='questionbase/static/img/question/', verbose_name='Файл к вопросу'),
        ),
        migrations.AddField(
            model_name='question',
            name='qlink3',
            field=models.FileField(blank=True, upload_to='questionbase/static/img/question/', verbose_name='Файл к вопросу'),
        ),
        migrations.DeleteModel(
            name='aLinks',
        ),
        migrations.DeleteModel(
            name='qLinks',
        ),
    ]
