# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0014_auto_20171016_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qlink1type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
