# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0015_question_qlink1type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qlink1type',
        ),
    ]
