# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0016_remove_question_qlink1type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtextlower',
            field=models.TextField(blank=True, verbose_name='Вопрос'),
        ),
    ]
