# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0017_question_qtextlower'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerlower',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='commentlower',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
