# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0018_auto_20171026_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_is_audio',
            field=models.BooleanField(default=False, verbose_name='Вопрос с аудио'),
        ),
        migrations.AddField(
            model_name='question',
            name='q_is_img',
            field=models.BooleanField(default=False, verbose_name='Вопрос с картинкой'),
        ),
        migrations.AddField(
            model_name='question',
            name='q_is_video',
            field=models.BooleanField(default=False, verbose_name='Вопрос с видео'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_bb',
            field=models.BooleanField(default=False, verbose_name='ЧЯ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_played',
            field=models.BooleanField(default=False, verbose_name='Игралось'),
        ),
    ]
