# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0019_auto_20171026_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_is_audio',
            new_name='q_has_audio',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q_is_img',
            new_name='q_has_img',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q_is_video',
            new_name='q_has_video',
        ),
        migrations.AddField(
            model_name='question',
            name='q_has_media',
            field=models.BooleanField(default=False, verbose_name='Вопрос с медиа файлом'),
        ),
        migrations.AddField(
            model_name='question',
            name='wow',
            field=models.CharField(choices=[('WOW', 'wow'), ('-', '-'), ('FOO', 'foo')], default='-', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='alink1',
            field=models.FileField(blank=True, upload_to='static/img/answer/', verbose_name='Файл к ответу 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alink2',
            field=models.FileField(blank=True, upload_to='static/img/answer/', verbose_name='Файл к ответу 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alink3',
            field=models.FileField(blank=True, upload_to='static/img/answer/', verbose_name='Файл к ответу 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qlink1',
            field=models.FileField(blank=True, upload_to='static/img/question/', verbose_name='Файл к вопросу 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qlink2',
            field=models.FileField(blank=True, upload_to='static/img/question/', verbose_name='Файл к вопросу 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qlink3',
            field=models.FileField(blank=True, upload_to='static/img/question/', verbose_name='Файл к вопросу 3'),
        ),
    ]
