# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0020_auto_20171030_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='wow',
            field=models.CharField(choices=[('WOW', 'WOW'), ('-', '-'), ('FOO', 'FOO')], default='-', max_length=3),
        ),
    ]
