# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0023_question_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answerlower',
        ),
        migrations.RemoveField(
            model_name='question',
            name='commentlower',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qtextlower',
        ),
        migrations.AlterField(
            model_name='question',
            name='alink1',
            field=models.FileField(blank=True, upload_to='answer/', verbose_name='Файл к ответу 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alink2',
            field=models.FileField(blank=True, upload_to='answer/', verbose_name='Файл к ответу 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alink3',
            field=models.FileField(blank=True, upload_to='answer/', verbose_name='Файл к ответу 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qlink1',
            field=models.FileField(blank=True, upload_to='question/', verbose_name='Файл к вопросу 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qlink2',
            field=models.FileField(blank=True, upload_to='question/', verbose_name='Файл к вопросу 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qlink3',
            field=models.FileField(blank=True, upload_to='question/', verbose_name='Файл к вопросу 3'),
        ),
    ]
