# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0024_auto_20171114_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('chgk', 'ЧГК'), ('br', 'Брэйн'), ('tele', 'Теледомик')], default='chgk', max_length=4),
        ),
    ]
