# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0025_question_qtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('chgk', 'ЧГК'), ('br', 'Брэйн'), ('tele', 'Теледомик')], default='chgk', max_length=4, verbose_name='Тип вопроса'),
        ),
    ]
