# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0027_auto_20171120_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blitz',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blitz', to='questionbase.Question'),
        ),
    ]
