# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0028_auto_20171120_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blitz',
            old_name='qt1xt2',
            new_name='qtext2',
        ),
    ]
