# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0029_auto_20171120_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('is_done', models.BooleanField(default=False, verbose_name='Готово')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='questionbase.Package')),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questionbase.Question')),
            ],
        ),
    ]
