# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0032_auto_20171215_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetail',
            name='num_in_pkg',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер вопроса'),
        ),
    ]
